=== thedamoes/Gravitation/Gravitation/Gravitation/Maps/mapSpecificationScheema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="mapSpecificationScheema.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Map">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Surfaces">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BackgoundPicture">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="AssetName" type="xs:string" />
                    <xs:element name="Scale" type="xs:unsignedByte" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="MapWalls">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Wall">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Asset">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Height" type="xs:unsignedShort" />
                                <xs:element name="Width" type="xs:unsignedShort" />
                                <xs:element name="Scale">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="X" type="xs:decimal" />
                                      <xs:element name="Y" type="xs:decimal" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Rotation" type="xs:decimal" />
                                <xs:element name="Position">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="X" type="xs:integer" />
                                      <xs:element name="Y" type="xs:integer" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="name" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="walltype" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Obsticals">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Asset">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Height" type="xs:unsignedByte" />
                          <xs:element name="Width" type="xs:unsignedByte" />
                          <xs:element name="Scale">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="X" type="xs:unsignedByte" />
                                <xs:element name="Y" type="xs:unsignedByte" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Position">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="X" type="xs:unsignedByte" />
                                <xs:element name="Y" type="xs:unsignedByte" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Powerups">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Powerup">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Asset">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Height" type="xs:unsignedByte" />
                          <xs:element name="Width" type="xs:unsignedByte" />
                          <xs:element name="Scale">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="X" type="xs:unsignedByte" />
                                <xs:element name="Y" type="xs:unsignedByte" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Position">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="X" type="xs:unsignedByte" />
                                <xs:element name="Y" type="xs:unsignedByte" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="powerupType" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== thedamoes/Gravitation/Gravitation/Gravitation/Maps/firstLevel.xml
<?xml version="1.0"?>

<Map
xmlns="mapSpecificationScheema.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="mapSpecificationScheema.xsd">
  <MapDimentions>
    <Width>500</Width>
    <Height>500</Height>
  </MapDimentions>
  <Surfaces>
    <BackgoundPicture>
      <Asset name="grid">
        <Scale>
          <X>4</X>
          <Y>3</Y>
        </Scale>
        <Rotation>0.0</Rotation>
        <Position>
          <X>0</X>
          <Y>-500</Y>
        </Position>
      </Asset>
    </BackgoundPicture>
    <MapWalls>
      <Wall walltype="left">
        <Asset name="longWall">
          <Height>300</Height>
          <Width>100</Width>
          <Scale>
            <X>1</X>
            <Y>1</Y>
          </Scale>
          <Rotation>0.0</Rotation>
          <Position>
            <X>0</X>
            <Y>0</Y>
          </Position>
        </Asset>
      </Wall>

      <Wall walltype="right">
        <Asset name="longWall">
          <Height>300</Height>
          <Width>100</Width>
          <Scale>
            <X>1</X>
            <Y>1</Y>
          </Scale>
          <Rotation>0.0</Rotation>
          <Position>
            <X>500</X>
            <Y>0</Y>
          </Position>
        </Asset>
      </Wall>

      <Wall walltype="bottom">
        <Asset name="longPlatform">
          <Height>100</Height>
          <Width>300</Width>
          <Scale>
            <X>1</X>
            <Y>1</Y>
          </Scale>
          <Rotation>0.0</Rotation>
          <Position>
            <X>0</X>
            <Y>0</Y>
          </Position>
        </Asset>
      </Wall>


      <Wall walltype="top">
        <Asset name="longPlatform">
          <Height>100</Height>
          <Width>300</Width>
          <Scale>
            <X>1</X>
            <Y>1</Y>
          </Scale>
          <Rotation>0.0</Rotation>
          <Position>
            <X>0</X>
            <Y>-500</Y>
          </Position>
        </Asset>
      </Wall>


    </MapWalls>
    <Obsticals>
      <Asset name="wall">
        <Height>100</Height>
        <Width>100</Width>
        <Scale>
          <X>1</X>
          <Y>1</Y>
        </Scale>
        <Position>
          <X>0</X>
          <Y>0</Y>
        </Position>
      </Asset>
    </Obsticals>
  </Surfaces>
  <Powerups>
    <Position>
      <X>0</X>
      <Y>0</Y>
    </Position>
  </Powerups>
  <SpawnPoint>
    <Player1>
      <X>100</X>
      <Y>-100</Y>
    </Player1>
    <Player2>
      <X>300</X>
      <Y>-100</Y>
    </Player2>
    <default>
      <X>100</X>
      <Y>0</Y>
    </default>
  </SpawnPoint>

</Map>

=== thedamoes/Gravitation/Gravitation/Gravitation/Maps/level1.xml
<?xml version="1.0"?>

<Map
xmlns="mapSpecificationScheema.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="mapSpecificationScheema.xsd">
  <MapDimentions>
    <Width>2100</Width>
    <Height>1100</Height>
  </MapDimentions>
	<Surfaces>
    <BackgoundPicture>
      <Asset name="smudgystars">
        <Scale>
          <X>2</X>
          <Y>2</Y>
        </Scale>
        <Rotation>0.0</Rotation>
        <Position>
          <X>0</X>
          <Y>-800</Y>
        </Position>
      </Asset>
		</BackgoundPicture>
		<MapWalls>
			<Wall walltype="left">
				<Asset name="Maps/Map1/leftWall">
					<Height>300</Height>
					<Width>100</Width>
					<Scale>
						<X>4</X>
						<Y>4</Y>
					</Scale>
          <Rotation>0.0</Rotation>
					<Position>
            <X>-1690</X>
            <Y>-1180</Y>
					</Position>
				</Asset>
			</Wall>
			
			<Wall walltype="right">
				<Asset name="Maps/Map1/rightWall">
					<Height>300</Height>
					<Width>100</Width>
					<Scale>
						<X>4</X>
						<Y>4</Y>
					</Scale>
          <Rotation>0.0</Rotation>
					<Position>
            <X>3670</X>
            <Y>-440</Y>
					</Position>
				</Asset>
			</Wall>

			<Wall walltype="bottom">
				<Asset name="Maps/Map1/bottomWall">
					<Height>100</Height>
					<Width>300</Width>
					<Scale>
						<X>4</X>
						<Y>4</Y>
					</Scale>
          <Rotation>0.0</Rotation>
					<Position>
						<X>1050</X>
            <Y>1000</Y>
					</Position>
				</Asset>
			</Wall>

		
			<Wall walltype="top">
				<Asset name="Maps/Map1/topWall">
					<Height>100</Height>
					<Width>300</Width>
					<Scale>
						<X>4</X>
						<Y>4</Y>
					</Scale>
          <Rotation>0.0</Rotation>
					<Position>
						<X>1950</X>
						<Y>-2525</Y>
					</Position>
				</Asset>
			</Wall>


		</MapWalls>

		<Obsticals>
			<Asset name="rock2f">
					<Height>100</Height>
					<Width>100</Width>
					<Scale>
						<X>1</X>
						<Y>1</Y>
					</Scale>
          <Rotation>2.0</Rotation>
					<Position>
						<X>500</X>
						<Y>-500</Y>
					</Position>
			</Asset>

      <Asset name="rock2f">
        <Height>100</Height>
        <Width>100</Width>
        <Scale>
          <X>1</X>
          <Y>1</Y>
        </Scale>
        <Position>
          <X>1000</X>
          <Y>-300</Y>
        </Position>
      </Asset>
      
		</Obsticals>

	</Surfaces>
	<Powerups>
      <Position>
        <X>10</X>
        <Y>0</Y>
      </Position>
    <Position>
      <X>15</X>
      <Y>0</Y>
    </Position>
    <Position>
      <X>20</X>
      <Y>0</Y>
    </Position>
  	</Powerups>
  <SpawnPoint>
    <Player1>
      <X>1000</X>
      <Y>0</Y>
    </Player1>
    <Player2>
      <X>2000</X>
      <Y>0</Y>
    </Player2>
    <default>
      <X>600</X>
      <Y>0</Y>
    </default>
  </SpawnPoint>
	
</Map>
